#!/usr/bin/python
# -*- coding: utf-8 -*-

#import re
import sys

from sphinx.quickstart import generate
if __name__ == '__main__':
    print 'Argument List:', str(sys.argv)   
    d= {
        'path': sys.argv[1],
        'sep': True,
        'dot': '_',
		'project': sys.argv[2],
        'author': sys.argv[3],
        'version': sys.argv[4],
        'release': sys.argv[4],
        'suffix': '.rst',
        'master': 'index',
        'epub': False,
        'ext_autodoc': False,
        'ext_doctest': False,
        'ext_coverage': False,
        'ext_pngmath': False,
        'ext_mathiax': False,
        'ext_viewcode': False,
        'makefile': True,
        'batchfile': False,
		'language': 'de',
    }
    generate(d)
